image: maven:latest

variables:
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository/
    - target/
clean:
  stage: clean
  script:
   - mvn $MAVEN_CLI_OPTS clean
build:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS compile

test:
  stage: test
  script:
    - mvn $MAVEN_CLI_OPTS test

deploy:
  before_script:
    - export COMMIT_TIME=$(git show -s --format=%ct $CI_COMMIT_SHA)
  stage: deploy
  script:
    - mvn $MAVEN_CLI_OPTS package
    - ssh-keygen -t rsa -b 4096 -C '' -f ~/.ssh/deploy_rsa
    - ssh-keyscan -H madfix.me >> ~/.ssh/known_hosts
    - ssh-copy-id -i ~/.ssh/deploy_rsa.pub $SERVER_USER@madfix.me
    - rsync --delete -avzbe 'ssh -i /pfad/zur/id_rsa' $SERVER_USER@example.com:/var/www /home/benutzer/webserver
    - rsync -avuz $CI_PROJECT_DIR/traget/*.jar $SERVER_USER@madfix.me:/srv/www/update.madfix.me/public_html/projects/MaterialDesignWebInterface/module/
  artifacts:
    paths:
      - "target/*.jar"
