image: maven:latest

variables:
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository/
    - target/
test:
  stage: test
  script:
    - mvn $MAVEN_CLI_OPTS test
  before_script:
    - apt-get update -qq && apt-get install -y -qq sshpass
    - mvn $MAVEN_CLI_OPTS clean
deploy-build:
  stage: deploy
  script:
    - apt-get update -qq && apt-get install -y -qq sshpass
    - mvn $MAVEN_CLI_OPTS package
    - cd target/
    - ls
    - sshpass -V
    - export SSHPASS=$USER_PASS
    - sshpass -v -e scp -o StrictHostKeyChecking=no -r target/*.jar cloudnet@madfix.me:/srv/www/update.madfix.me/public_html/projects/MaterialDesignWebInterface/module/
  artifacts:
    paths:
      - "target/*.jar"
